## Grafana Chart customizations

# Setup autodiscovery of grafana datasources
# If a datasource is tagged with grafana_datasource '1' as in config.yaml, it will show up in grafana
sidecar:
  datasources:
    enabled: true
    label: grafana_datasource

# Set up grafana.com dashboard provider
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default 

# Configure dashboards which are pulled from grafana.com
dashboards:
  default:
    node-exporter:
      gnetId: 1860
      revision: 14
      datasource: Prometheus
    prometheus-2:
      gnetId: 3662
      revision: 2
      datasource: Prometheus

# Configure persistence so changes are saved between upgrades
persistence:
  type: pvc
  enabled: true 
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  finalizers:
    - kubernetes.io/pvc-protection